import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

function formatTrustedHostsYaml(trustedHosts: readonly string[]): string {
  if (trustedHosts.length === 0) return '    trustedHosts: []'
  return `    trustedHosts:\n${trustedHosts.map(entry => `      - ${JSON.stringify(entry)}`).join('\n')}`
}

/**
 * Write a Cordis overlay with an absolute WeKnora plugin path. The loader accepts
 * `!!js` only under `config`, not on plugin `name`.
 * @param calbPluginRoot - root of @shangeyao/dsh-calb-plugin.
 * @param trustedHosts - LAN / deployment authorities for dsh web-runtime and /api fence.
 * @returns absolute path of the generated overlay file.
 */
export async function writeRuntimePatch(
  calbPluginRoot: string,
  trustedHosts: readonly string[],
): Promise<string> {
  const weknoraPath = join(calbPluginRoot, 'dist/weknora/index.js')
  const sharedModelsPath = join(calbPluginRoot, 'shared-models/dist/index.js')
  const patchPath = join(calbPluginRoot, 'cordis.runtime.patch.yml')
  const content = `# Generated by calb-gateway — do not edit.
- id: web-runtime
  config:
    printUrl: true
    openBrowser: false
    surfaceContext: true
${formatTrustedHostsYaml(trustedHosts)}

- insert:
    - id: weknora
      name: ${JSON.stringify(weknoraPath)}
      config: {}
    - id: calb-shared-models
      name: ${JSON.stringify(sharedModelsPath)}
      config: {}
`
  await writeFile(patchPath, content, 'utf8')
  return patchPath
}
