/**
 * Emit the unified CALB host half as a thin re-export entry (no bundling).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const outFile = join(root, 'dist/index.js')

mkdirSync(dirname(outFile), { recursive: true })

writeFileSync(outFile, `/**
 * Unified CALB plugin host entry: WeKnora tools, shared model policy, and account UI.
 * Generated by build-host.mjs — do not edit.
 */
import { apply as applyWeknora } from './weknora/index.js'
import { apply as applySharedModels } from '../shared-models/dist/index.js'
import { apply as applyAccountUi } from '../account-ui/dist/index.js'

export const name = 'dsh-calb-plugin'

export const inject = ['tools', 'settings', 'credentials', 'webServer']

/** @param {unknown} ctx @param {unknown} [config] */
export function apply(ctx, config) {
  applyWeknora(ctx, config)
  applySharedModels(ctx)
  applyAccountUi(ctx)
}
`)
